apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: docker-lg2
  name: docker-lg2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: docker-lg2
    spec:
      containers:
      - image: neotys/neoload-loadgenerator:6.7.0
        name: docker-lg2
        resources: {}
      restartPolicy: Always
status: {}
